name: flutter_template

packages:
  - foundation
  - service_entity
  - service
  - repository
  - domain_entity
  - domain
  - interactor
  - presentation_entity
  - presentation
  - .

scripts:
  clean-all:
    run: melos run build-clean && melos run flutter-clean

  flutter-clean:
    exec: flutter clean

  build-clean:
    run: melos exec --scope="service,flutter_template,foundation" flutter pub run build_runner clean

  generate:
    run: melos exec --scope="service,flutter_template,foundation" -- flutter pub run build_runner build --delete-conflicting-outputs

  get:
    exec: flutter pub get

  tidy:
    run: melos run format && melos run dart-fix

  analyze:
    exec: flutter analyze --fatal-infos --fatal-warnings

  format:
    exec: flutter format .

  dart-fix:
    exec: dart fix --apply

  test:
    exec: flutter test --exclude-tags=golden

  test-update-golden:
    run: flutter test --tags=golden presentation/test/goldens --update-goldens

  test-golden:
    run: flutter test --tags=golden presentation/test/goldens
