name: Update Goldens
on: workflow_dispatch
jobs:
  update_goldens:
    name: Update Golden Files
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 'Install Tools'
        run: |
          ./.github/workflows/scripts/install-tools.sh

      - name: 'Bootstrap Workspace'
        run: melos bootstrap

      - name: Setup app_secrets.dart
        env:
          APP_SECRETS: ${{ secrets.APP_SECRETS }}
          APP_SECRETS_PATH: foundation/lib/src/secrets/app_secrets.dart
        run: echo -n $APP_SECRETS | base64 --decode > $APP_SECRETS_PATH

      - name: Get Dependencies
        run: melos run get

      - name: Run build_runner
        run: melos run generate

      - name: Generate Goldens
        run: melos run test-update-golden

      - name: Configure Git
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"

      - name: Commit changes
        run: git add test/presentation/goldens && git commit -m "Updated golden files"

      - uses: nelonoel/branch-name@v1.0.1

      - name: Push changes
        run: git push origin ${BRANCH_NAME}
